version: "3.3"

services:
  authentication:
    build: ./authService
    container_name: "wallet_auth_app"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./authService:/usr/src/app
    ports:
      - "9000:8000"

  celery:
    build: ./authService
    command:  celery -A authService worker -l info
    volumes:
      - ./authService:/usr/src/app
    env_file:
      - ./authService/authenv.env
    depends_on:
      - redis
      - authentication
  
  redis:
    image: redis:6-alpine
